### ISSUE TITLE
Error C2169 : 'lrint' : intrinsic function, cannot be defined in gfxPrimitives.c

### ISSUE THREAD

**Issue by Wakeelfahmed** [ferzkopp/SDL2_gfx#1]
https://github.com/ferzkopp/SDL2_gfx/blob/c4aca6b9700ec0db0abd316809e7e6038c511ce2/SDL2_gfxPrimitives.c#L1765

This issue is only coming in Release mode not in Debug mode
I thought it might be due to VS 22 but the same issue is coming in VS 19

![212164246-7869730b-763a-4e3d-ae26-7f5e1badd358](https://user-images.githubusercontent.com/67804908/212166770-fc91f742-9fdb-48d5-a9b6-3e36cb3858bb.png)

**Comment by ferzkopp** [comment]
Definition probably needs to be wrapped in: 
```
#if _MSC_VER < 1928
...
#endif
```

**Comment by Wakeelfahmed** [comment]
Take a look.
![image](https://user-images.githubusercontent.com/67804908/212473009-84529032-9f98-4088-ad2d-f53f88ab1b53.png)
not idea why line number is different but its the same line I marked on this issue
![image](https://user-images.githubusercontent.com/67804908/212473018-4f98752e-7ab0-4d3b-a034-4ad996159af7.png)

**Comment by Wakeelfahmed** [comment]
Thanks man! Ur advice fixed the issue
#if _MSC_VER < 1928
	lrint(double d)
{
	float f = (float)d;
	return _mm_cvtss_si32(_mm_load_ss(&f));

}
#endif

**Comment by Wakeelfahmed** [comment]
Thanks man! Ur advice fixed the issue
#if _MSC_VER < 1928
	lrint(double d)
{
	float f = (float)d;
	return _mm_cvtss_si32(_mm_load_ss(&f));

}
#endif
